---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ShardOS
description: Specialized host image for high-performance VMs and containers with dGPU passthrough and Image Building capabilities, built on the Zen Kernel.

# 1. BASE IMAGE: Using the Zen Kernel variant for high performance and low latency
base-image: ghcr.io/ublue-os/silverblue-main-zen
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # ADDED: Installs the ujust utility for running maintenance scripts
  - type: ujust

  # ADDED: Enables automatic background updates and desktop notifications
  - type: update-system 

  # 2. DNF/RPM-OSTREE: Install all core host packages and remove unwanted desktop RPMs
  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      # Essential user tools
      - micro
      - starship
      
      # VIRTUALIZATION & KVM (Host Hypervisor)
      - qemu-kvm
      - libvirt
      - libvirt-client
      - libvirt-daemon-kvm
      - libvirt-daemon-config-network
      - virt-install
      - edk2-ovmf
      - virt-viewer
      
      # CONTAINER MANAGEMENT (Core Tools)
      - podman
      - skopeo
      - buildah
      
      # SYSTEM MANAGEMENT, MONITORING, & TUNING
      - cockpit
      - cockpit-machines 
      - cockpit-podman
      - cockpit-files
      - cockpit-networkmanager
      - cockpit-selinux
      - cockpit-packagekit
      - cockpit-storaged
      - cockpit-pcp
      - pcp
      - python3-pcp
      - pcp-system-tools
      - tuned
      - sysstat
      
      # NETWORKING, STORAGE & FIREWALL
      - firewalld
      - iptables
      - openssh-server
      - cryptsetup
      - lvm2
      - mdadm
      
      # SECURITY & AUTHENTICATION
      - policycoreutils-python-utils 
      - setroubleshoot-server
      - audit
      - setools-console
      
      # HARDWARE FIRMWARE
      - fwupd
      - amd-ucode-firmware
      - microcode_ctl
      
      # OSBUILD COMPOSER
      - osbuild-composer
      - composer-cli
      
    remove: # Removing unnecessary desktop RPMs
      packages:
        - firefox 
        - firefox-langpacks 
        - gnome-calculator
        - gnome-contacts
        - gnome-maps
        - totem 
        - yelp 
        - gnome-text-editor 

  # 3. SERVICES: Enable essential daemons on boot
  - type: services
    enable:
      - libvirtd.service
      - pmlogger.service
      - osbuild-composer.socket

  # 4. GNOME DESKTOP MINIMALISM & iGPU ENFORCEMENT
  - type: gnome
    integrated-gpu-priority: true
    remove: 
      - gnome-tour
      - gnome-shell-extension-background-logo
      - rhythmbox
      - baobab 

  # 5. DEFAULT FLATPAKS: Essential Host Management GUI tools
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install: 
          - app.zen_browser.zen
          - org.gnome.Loupe
          - io.podman_desktop.PodmanDesktop
          - org.virt_manager.VirtManager
      - scope: user 

  # 6. SIGNING: Essential for secure image verification
  - type: signing
