name: ShardOS
description: Specialized host image for high-performance VMs and containers with dGPU passthrough and Image Building capabilities.
base-image: ghcr.io/ublue-os/silverblue-beta-zen
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
      - ublue-update
      - micro
      - starship
      - qemu-kvm
      - libvirt
      - libvirt-client
      - libvirt-daemon-kvm
      - libvirt-daemon-config-network
      - virt-install
      - edk2-ovmf
      - virt-viewer
      - podman
      - skopeo
      - buildah
      - podman-compose
      - podman-docker
      - containers-tools
      - libavcodec-freeworld
      - cockpit
      - cockpit-machines 
      - cockpit-podman
      - cockpit-files
      - cockpit-networkmanager
      - cockpit-selinux
      - cockpit-packagekit
      - cockpit-storaged
      - cockpit-pcp
      - pcp
      - python3-pcp
      - pcp-system-tools
      - tuned
      - sysstat
      - firewalld
      - iptables
      - openssh-server
      - cryptsetup
      - lvm2
      - mdadm
      - policycoreutils-python-utils 
      - setroubleshoot-server
      - audit
      - setools-console
      - fwupd
      - amd-ucode-firmware
      - microcode_ctl
      - osbuild-composer
      - composer-cli
    remove: 
      - firefox
      - firefox-langpacks
      - gnome-calculator
      - gnome-contacts
      - gnome-maps
      - totem
      - yelp
      - gnome-text-editor
      - gnome-tour
      - gnome-shell-extension-background-logo
      - rhythmbox
      - baobab

  - type: dnf
    repos:
      copr:
        - atim/starship

  - type: systemd
    enable:
      - libvirtd.service
      - virtlogd.service
      - virtqemud.service
      - sshd.service
      - cockpit.socket
      - firewalld.service
      - tuned.service
      - pmcd.service
      - pmlogger.service
      - auditd.service

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install: 
          - app.zen_browser.zen 
          - org.gnome.Loupe
          - io.podman_desktop.PodmanDesktop 
          - org.virt_manager.VirtManager 
          - io.github.kolunmi.Bazaar
        remove:
          - org.mozilla.firefox
      - scope: user 

  - type: signing
