# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ShardOS
description: Specialized host image for high-performance VMs and containers with dGPU passthrough and Image Building capabilities.

# 1. BASE IMAGE: Using the Zen Kernel variant for high performance and low latency
base-image: ghcr.io/ublue-os/silverblue-main-zen
image-version: latest

modules:
  # 1. CORE SYSTEM FILES
  - type: files
    files:
      - source: system
        destination: /

  # 2. ADD EXTERNAL REPOSITORIES 🚨 NEW MODULE ADDED 🚨
  # Installs the RPM files that define the repositories (RPM Fusion for codecs/drivers)
  - type: rpm
    install:
      # RPM Fusion (Free) for common software and multimedia codecs
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
      # RPM Fusion (Non-Free) for proprietary drivers and software
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
      
      # NOTE: Starship COPR is handled in the 'type: dnf' module below.

  # 3. DNF/RPM-OSTREE: Install Virtualization, Cockpit, SELinux Tools, and OSBuild Composer
  - type: dnf
    repos:
      # COPR for up-to-date Starship prompt (if not in RPM Fusion)
      copr:
        - atim/starship
    install:
      # 🚨 CORE UPDATE TOOL ADDED 🚨
      - ublue-update              # Core update management tool

      # Essential user tools
      - micro
      - starship
      
      # VIRTUALIZATION & KVM (Host Hypervisor)
      - qemu-kvm
      - libvirt
      - libvirt-client
      - libvirt-daemon-kvm
      - libvirt-daemon-config-network
      - virt-install
      - edk2-ovmf             # UEFI Firmware
      - virt-viewer           # Remote console viewer
      
      # CONTAINER MANAGEMENT (Core Tools)
      - podman
      - skopeo
      - buildah
      # 🚨 MISSING CONTAINER TOOLS ADDED 🚨
      - podman-compose          # Compose support for Cockpit Compose
      - podman-docker           # Docker compatibility symlinks
      - containers-tools        # Utility tools

      # 4. MULTIMEDIA/CODECS (Requires RPM Fusion to be enabled)
      - libavcodec-freeworld

      # SYSTEM MANAGEMENT, MONITORING, & TUNING
      - cockpit
      - cockpit-machines 
      - cockpit-podman
      - cockpit-files           # Cockpit file browser
      - cockpit-networkmanager  # Cockpit network module
      - cockpit-selinux         # Cockpit SELinux module
      - cockpit-packagekit
      - cockpit-storaged
      - cockpit-pcp
      - pcp                     # Core PCP package
      - python3-pcp             # Python bindings for PCP
      - pcp-system-tools
      - tuned                   # System performance tuner
      - sysstat
      
      # NETWORKING, STORAGE & FIREWALL
      - firewalld               # Host firewall
      - iptables
      - openssh-server
      - cryptsetup              # Disk encryption utility
      - lvm2                    # Logical Volume Manager
      - mdadm                   # Software RAID manager
      
      # SECURITY & AUTHENTICATION
      - policycoreutils-python-utils 
      - setroubleshoot-server
      - audit
      - setools-console
      
      # HARDWARE FIRMWARE
      - fwupd                   # Firmware Updater
      - amd-ucode-firmware      # AMD Microcode
      - microcode_ctl           # Intel/AMD Microcode Control
      
      # OSBUILD COMPOSER
      - osbuild-composer
      - composer-cli
      
    remove: 
      packages:
        - firefox 
        - firefox-langpacks 
        - gnome-calculator
        - gnome-contacts
        - gnome-maps
        - totem 
        - yelp 
        - gnome-text-editor 

  # 4. SERVICES: Enable essential daemons
  - type: services
    enable:
      - libvirtd.service 
      - pmlogger.service 
      - osbuild-composer.socket
      # 🚨 COCKPIT SERVICE ADDED 🚨
      - cockpit.socket

  # 5. GNOME DESKTOP MINIMALISM & iGPU ENFORCEMENT
  - type: gnome
    integrated-gpu-priority: true
    remove: 
      - gnome-tour
      - gnome-shell-extension-background-logo
      - rhythmbox
      - baobab 

  # 6. DEFAULT FLATPAKS: Essential Host Management
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install: 
          - app.zen_browser.zen 
          - org.gnome.Loupe
          # 🚨 BAZAAR FLATPAK ADDED 🚨
          - io.github.kolunmi.Bazaar
          - io.podman_desktop.PodmanDesktop 
          - org.virt_manager.VirtManager 
      - scope: user 

  # 7. SIGNING (No change needed)
  - type: signing
