# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ShardOS
description: Specialized host image for high-performance VMs and containers with dGPU passthrough and Image Building capabilities.

# BASE IMAGE: Using the BETA channel for the Zen Kernel variant
base-image: ghcr.io/ublue-os/silverblue-beta-zen
image-version: latest

modules:
  # 1. CORE SYSTEM FILES
  - type: files
    files:
      - source: system
        destination: /

  # 2. ADD EXTERNAL REPOSITORIES (RPM Fusion)
  - type: rpm
    install:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

  # 3. DNF/RPM-OSTREE: Package Management
  - type: dnf
    repos:
      # Starship COPR
      copr:
        - atim/starship
    install:
      # CORE & USER TOOLS
      - ublue-update
      - micro
      - starship
      
      # VIRTUALIZATION & KVM
      - qemu-kvm
      - libvirt
      - libvirt-client
      - libvirt-daemon-kvm
      - libvirt-daemon-config-network
      - virt-install
      - edk2-ovmf
      - virt-viewer
      
      # CONTAINER MANAGEMENT
      - podman
      - skopeo
      - buildah
      - podman-compose
      - podman-docker
      - containers-tools

      # MULTIMEDIA/CODECS (Requires RPM Fusion)
      - libavcodec-freeworld

      # SYSTEM MANAGEMENT, MONITORING, & TUNING
      - cockpit
      - cockpit-machines 
      - cockpit-podman
      - cockpit-files
      - cockpit-networkmanager
      - cockpit-selinux
      - cockpit-packagekit
      - cockpit-storaged
      - cockpit-pcp
      - pcp
      - python3-pcp
      - pcp-system-tools
      - tuned
      - sysstat
      
      # NETWORKING, STORAGE & FIREWALL
      - firewalld
      - iptables
      - openssh-server
      - cryptsetup
      - lvm2
      - mdadm
      
      # SECURITY & AUTHENTICATION
      - policycoreutils-python-utils 
      - setroubleshoot-server
      - audit
      - setools-console
      
      # HARDWARE FIRMWARE
      - fwupd
      - amd-ucode-firmware
      - microcode_ctl
      
      # OSBUILD COMPOSER
      - osbuild-composer
      - composer-cli
      
    remove: 
      packages:
        # CONSOLIDATED REMOVALS LIST
        - firefox
        - firefox-langpacks
        - gnome-calculator
        - gnome-contacts
        - gnome-maps
        - totem
        - yelp
        - gnome-text-editor
        # REMOVED FROM type: gnome MODULE
        - gnome-tour
        - gnome-shell-extension-background-logo
        - rhythmbox
        - baobab

  # 4. SERVICES: Enable essential daemons
  - type: services
    enable:
      - libvirtd.service 
      - pmlogger.service 
      - osbuild-composer.socket
      - cockpit.socket

  # 5. FLATPAK REMOTE FIX
  - type: flatpak-remote
    install:
      # Guarantees Flathub remote is available
      - remote: flathub
        url: https://flathub.org/repo/flathub.flatpakrepo
        system: true

  # 6. GNOME DESKTOP MINIMALISM (REMOVAL LIST IS NOW EMPTY)
  - type: gnome
    integrated-gpu-priority: true
    # The 'remove' section was removed from here.

  # 7. DEFAULT FLATPAKS: System Scope Apps
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install: 
          - app.zen_browser.zen 
          - org.gnome.Loupe
          - io.podman_desktop.PodmanDesktop 
          - org.virt_manager.VirtManager 
          - io.github.kolunmi.Bazaar
        remove:
          # Removes Firefox Flatpak (fixes auto-install)
          - org.mozilla.firefox
      - scope: user 

  # 8. SIGNING
  - type: signing
